define({
  "title": "hapi-learning API documentation",
  "order": [
    "Login",
    "Logout",
    "Me",
    "PatchMe",
    "MeCourses",
    "MeCoursesNews",
    "GetCourses",
    "GetCourse",
    "GetCourseHomepage",
    "GetCourseTree",
    "GetCourseDocuments",
    "GetCourseStudents",
    "PostCourse",
    "PostDocument",
    "CreateFolder",
    "PostHomepage",
    "UpdateFile",
    "AddTags",
    "AddTeachers",
    "PatchCourse",
    "DeleteCourse",
    "DeleteCourseTags",
    "DeleteCourseTeachers",
    "DeleteCourseDocuments",
    "GetTags",
    "GetTag",
    "PostTag",
    "DeleteTag",
    "GetManyNews",
    "GetOneNews",
    "PostNews"
  ],
  "name": "hapi-learning",
  "version": "1.0.0",
  "description": "e-learning platform built with hapijs and angular",
  "sampleUrl": false,
  "apidoc": "0.2.0",
  "generator": {
    "name": "apidoc",
    "time": "2015-12-11T11:47:20.186Z",
    "url": "http://apidocjs.com",
    "version": "0.13.1"
  }
});